### ISSUE TITLE
Can't use the SDK with vite

### ISSUE THREAD

**Issue by herzaso** [harmony-one/sdk#102]
After installing the crypto package via `yarn add @harmony-js/crypto` (installed v0.1.56), starting the application produces the following error:
```
yarn run v1.22.11
$ vite
 > node_modules/vite/dist/node/chunks/dep-98dbe93b.js:39126:14: error: [plugin: vite:dep-scan] Failed to resolve entry for package "@harmony-js/crypto". The package may have incorrect main/module/exports specified in its package.json.
    39126 │         throw new Error(`Failed to resolve entry for package "${id}". ` +
          ╵               ^
    at resolvePackageEntry (/home/ofir/Development/private/test/node_modules/vite/dist/node/chunks/dep-98dbe93b.js:39126:15)
    at tryNodeResolve (/home/ofir/Development/private/test/node_modules/vite/dist/node/chunks/dep-98dbe93b.js:38938:11)
    at Context.resolveId (/home/ofir/Development/private/test/node_modules/vite/dist/node/chunks/dep-98dbe93b.js:38819:28)
    at Object.resolveId (/home/ofir/Development/private/test/node_modules/vite/dist/node/chunks/dep-98dbe93b.js:51254:55)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async resolve (/home/ofir/Development/private/test/node_modules/vite/dist/node/chunks/dep-98dbe93b.js:51453:26)
    at async /home/ofir/Development/private/test/node_modules/vite/dist/node/chunks/dep-98dbe93b.js:51565:34
    at async callback (/home/ofir/Development/private/test/node_modules/esbuild/lib/main.js:812:28)
    at async handleRequest (/home/ofir/Development/private/test/node_modules/esbuild/lib/main.js:644:30)

   node_modules/vite/dist/node/chunks/dep-98dbe93b.js:51555:18: note: This error came from the "onResolve" callback registered here
    51555 │             build.onResolve({
          ╵                   ~~~~~~~~~
    at setup (/home/ofir/Development/private/test/node_modules/vite/dist/node/chunks/dep-98dbe93b.js:51555:19)
    at handlePlugins (/home/ofir/Development/private/test/node_modules/esbuild/lib/main.js:736:23)
    at Object.buildOrServe (/home/ofir/Development/private/test/node_modules/esbuild/lib/main.js:1024:7)
    at /home/ofir/Development/private/test/node_modules/esbuild/lib/main.js:1754:17
    at new Promise (<anonymous>)
    at Object.build (/home/ofir/Development/private/test/node_modules/esbuild/lib/main.js:1753:14)
    at Object.build (/home/ofir/Development/private/test/node_modules/esbuild/lib/main.js:1629:51)
    at /home/ofir/Development/private/test/node_modules/vite/dist/node/chunks/dep-98dbe93b.js:51412:54
    at Array.map (<anonymous>)

   src/services/tokens.js:2:31: note: The plugin "vite:dep-scan" was triggered by this import
        2 │ import { HarmonyAddress } from '@harmony-js/crypto';
          ╵                                ~~~~~~~~~~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 1 error:
node_modules/vite/dist/node/chunks/dep-98dbe93b.js:39126:14: error: [plugin: vite:dep-scan] Failed to resolve entry for package "@harmony-js/crypto". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (/home/ofir/Development/private/test/node_modules/esbuild/lib/main.js:1449:15)
    at /home/ofir/Development/private/test/node_modules/esbuild/lib/main.js:1131:28
    at runOnEndCallbacks (/home/ofir/Development/private/test/node_modules/esbuild/lib/main.js:921:63)
    at buildResponseToResult (/home/ofir/Development/private/test/node_modules/esbuild/lib/main.js:1129:7)
    at /home/ofir/Development/private/test/node_modules/esbuild/lib/main.js:1236:14
    at /home/ofir/Development/private/test/node_modules/esbuild/lib/main.js:609:9
    at handleIncomingPacket (/home/ofir/Development/private/test/node_modules/esbuild/lib/main.js:706:9)
    at Socket.readFromStdout (/home/ofir/Development/private/test/node_modules/esbuild/lib/main.js:576:7)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:470:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by PandaSekh** [comment]
I tried to reproduce this with a minimal repo (vite with vue template) without success.
@herzaso do you have any plugin installed? Can you please post the package.json?

**Comment by signorbusi** [comment]
I created a minimal repo that reproduces the problem: https://github.com/signorbusi/vite-react-app

```bash
git clone https://github.com/signorbusi/vite-react-app && cd vite-react-app
pnpm install
pnpm dev
```
